global:
  resolve_timeout: 5m
route:
  receiver: webhook
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 5m
  group_by: [alertname]
  routes:
  - receiver: webhook
    group_wait: 10s
    match:
      team: node
receivers:
- name: webhook
  webhook_configs:
  - url: http://root:root@127.0.0.1:9119/alert
    send_resolved: true
